#!/usr/bin/env bash

function create_k3d_cluster() {
  k3d cluster create --config ${config_path} ${cluster_name}
  k3d kubeconfig write ${cluster_name} --output ${kubeconfig_path}
}

create_k3d_cluster